---
- name: install wireshark on web, nfs and db servers
  hosts: webservers, nfs
  remote_user: ec2-user
  become: yes
  tasks:
    - name: install git
      yum:
        name: git
        state: latest
    
    - name: install mysql client
      yum:
        name: mysql-common
        state: latest

    - name: ensure wireshark is at the latest version
      yum:
        name: wireshark
        state: latest

- name: update LB server
  hosts: loadbalancer
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Update apt repo
      apt: 
        update_cache: yes
    
    - name: install git
      apt:
        name: git
        state: latest
    
    - name: install mysql client
      apt:
        name: mysql-common
        state: latest
     
    - name: ensure wireshark is at the latest version
      apt:
        name: wireshark
        state: latest