---
- name: Include dynamic variables
  hosts: all

- name: import the common playbook
  import_playbook: ../static-assignments/common.yml
  tags:
    - always


- name: include the env-vars playbook
  import_playbook: ../dynamic-assignments/env-vars.yml
  tags:
    - always

# # configure jenkins server
# - name: jenkins assignment
#   import_playbook: ../static-assignments/jenkins.yml

# configure nfs server
- name: loading play for NFS server(s)
  import_playbook: ../static-assignments/nfs.yml

# configure database server
- name: loading play for database server(s)
  import_playbook: ../static-assignments/db.yml

# configure webservers
- name: Webserver assignment
  import_playbook: ../static-assignments/webservers.yml

# # setup ssl
- name: Letsencrypt assignment
  import_playbook: ../static-assignments/letsencrypt.yml
  when: load_balancer_is_required

# # configure loadbalancer
- name: Loadbalancers assignment
  import_playbook: ../static-assignments/loadbalancers.yml
  when: load_balancer_is_required


